# Generated by Django 4.2.2 on 2023-10-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sale',
            new_name='is_on_sale',
        ),
    ]
